language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
services:
  - mongodb
before_script:
  - npm install grunt-cli -g
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start 2>&1 &" - sleep 5
